version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./containers/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: quote_editor
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
